### ISSUE TITLE
Get rancher desktop to work

### ISSUE THREAD

**Issue by castrojo** [castrojo/ublue#17]
This would be nice-to-have for people coming from docker desktop. It installs, the app runs, but the underlying guts (it's complicated in there). I don't expect us to be able to figure this out but filing this anyway.

**Comment by tepene** [comment]
Since my tests in a silverblue vm with the rancher desktop appimage never worked I tried to install it in a distrobox. Everything was running except the vscode integration. Since my dev workflow heavily depends on vscode devcontainers I finally gave it another try and to my surprise the appimage [v1.4.1](https://download.opensuse.org/repositories/isv:/Rancher:/stable/AppImage/rancher-desktop-latest-x86_64.AppImage) seams to work.

**Installation**
```sh
wget -O ~/.local/bin/rancher-desktop.AppImage https://download.opensuse.org/repositories/isv:/Rancher:/stable/AppImage/rancher-desktop-latest-x86_64.AppImage

chmod +x ~/.local/bin/rancher-desktop.AppImage 
```

**Desktop Entry**
```ini
# ~/.local/share/applications
## -> Note: Edit Exec path with your home dir. $HOME and ~ don't seem to work

[Desktop Entry]
Name=Rancher Desktop
Exec=/var/home/lus/.local/bin/rancher-desktop.AppImage
Terminal=false
Type=Application
Icon=rancher-desktop
StartupWMClass=Rancher Desktop
Categories=Development;
```

**My current settings**
![image](https://user-images.githubusercontent.com/54766327/173385048-988f4134-1bc7-496c-a4ba-d5cfc15609b4.png)

**After first start**
```sh
docker context use rancher-desktop
```

**Comment by castrojo** [comment]
This is great! Maybe we can script this up...

**Comment by tepene** [comment]
> This is great! Maybe we can script this up...

I'll give it a try
